name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: './Client/package-lock.json'

      - name: Install Dependencies
        run: |
          npm install
          npm ci

      - name: Type Check
        run: npm run check-types

      - name: Run Unit Tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create E2E Test Directories
        run: |
          mkdir -p src/e2e/.auth
          mkdir -p src/e2e/test-results
          echo '{"cookies":[],"origins":[]}' > src/e2e/.auth/user.json

      - name: Run E2E Tests
        run: npm run test:e2e
        env:
          CI: true
          PLAYWRIGHT_HTML_REPORT: ./src/e2e/test-results
          NODE_ENV: test
          # Add any API endpoints or other environment variables if needed
          # API_URL: ${{ secrets.API_URL }}

      - name: Upload E2E Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./Client/src/e2e/test-results/
          retention-days: 7

      - name: Build Frontend
        run: npm run build

  backend:
    name: Backend Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display Structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "API directory contents:"
          ls -la API/
          echo "TenXCards.Api directory contents:"
          ls -la API/TenXCards.Api/

      - name: Restore Solution Dependencies
        working-directory: API
        run: dotnet restore TenXCards.sln
        env:
          DOTNET_ENVIRONMENT: Development
          ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}
          JWT__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
          JWT__Issuer: ${{ secrets.JWT_ISSUER }}
          JWT__Audience: ${{ secrets.JWT_AUDIENCE }}

      - name: Build Solution
        working-directory: API
        run: dotnet build TenXCards.sln --configuration Release --no-restore
        env:
          DOTNET_ENVIRONMENT: Development
          ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}
          JWT__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
          JWT__Issuer: ${{ secrets.JWT_ISSUER }}
          JWT__Audience: ${{ secrets.JWT_AUDIENCE }}

      # - name: Run Tests
      #   working-directory: API
      #   run: dotnet test TenXCards.sln --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      #   env:
      #     DOTNET_ENVIRONMENT: Development
      #     ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}
      #     JWT__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
      #     JWT__Issuer: ${{ secrets.JWT_ISSUER }}
      #     JWT__Audience: ${{ secrets.JWT_AUDIENCE }}

      - name: Upload Backend Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: ./API/TestResults/
          retention-days: 7

  # deploy:
  #   name: Deploy to Render
  #   needs: [frontend, backend]
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Deploy to Render
  #       env:
  #         RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
  #       run: |
  #         curl -X GET "$RENDER_DEPLOY_HOOK_URL" 