name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: './Client/package-lock.json'

      - name: Install Dependencies
        run: |
          npm install
          npm ci

      - name: Type Check
        run: npm run check-types

      - name: Run Unit Tests
        run: npm run test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create E2E Test Directories
        run: |
          mkdir -p src/e2e/.auth
          mkdir -p src/e2e/test-results
          echo '{"cookies":[],"origins":[]}' > src/e2e/.auth/user.json

      - name: Kill any existing processes on port 5173
        run: |
          lsof -ti:5173 | xargs -r kill -9 || true

      - name: Run E2E Tests
        run: |
          # Start the dev server in the background
          npm run dev:e2e &
          # Wait for the server to be ready
          npx wait-on http://localhost:5173
          # Run the tests
          npx playwright test
        env:
          CI: true
          PLAYWRIGHT_HTML_REPORT: ./src/e2e/test-results
          NODE_ENV: test
          PORT: 5173

      - name: Upload E2E Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./Client/src/e2e/test-results/
          retention-days: 7

      - name: Build Frontend
        run: npm run build

  backend:
    name: Backend Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Display Structure
        run: |
          pwd
          echo "Repository root contents:"
          ls -la
          echo "API directory contents:"
          ls -la API/
          echo "API solution file:"
          ls -la API/TenXCards.sln

      - name: Restore Solution Dependencies
        run: |
          cd API
          dotnet restore
        env:
          DOTNET_ENVIRONMENT: Development
          ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}
          JWT__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
          JWT__Issuer: ${{ secrets.JWT_ISSUER }}
          JWT__Audience: ${{ secrets.JWT_AUDIENCE }}

      - name: Build Solution
        run: |
          cd API
          dotnet build --configuration Release --no-restore
        env:
          DOTNET_ENVIRONMENT: Development
          ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}
          JWT__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
          JWT__Issuer: ${{ secrets.JWT_ISSUER }}
          JWT__Audience: ${{ secrets.JWT_AUDIENCE }}

      # - name: Run Tests
      #   working-directory: API
      #   run: dotnet test TenXCards.sln --no-restore --verbosity normal --collect:"XPlat Code Coverage"
      #   env:
      #     DOTNET_ENVIRONMENT: Development
      #     ConnectionStrings__DefaultConnection: ${{ secrets.DATABASE_CONNECTION_STRING }}
      #     JWT__SecretKey: ${{ secrets.JWT_SECRET_KEY }}
      #     JWT__Issuer: ${{ secrets.JWT_ISSUER }}
      #     JWT__Audience: ${{ secrets.JWT_AUDIENCE }}

      - name: Upload Backend Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: ./API/TestResults/
          retention-days: 7

  # deploy:
  #   name: Deploy to Render
  #   needs: [frontend, backend]
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Deploy to Render
  #       env:
  #         RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
  #       run: |
  #         curl -X GET "$RENDER_DEPLOY_HOOK_URL" 